FROM centos/java:8

WORKDIR /app

ADD ./build/libs/api-gateway-0.0.1.jar /app
RUN ln -s api-gateway-0.0.1.jar api-gateway-latest.jar

ADD ./wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it


CMD java -jar /app/api-gateway-latest.jar
