stage 'Stage 1. Checkout repo'

node('test_slave') {
	node('test_slave') {sh 'get from git'}
}

stage 'State 2. test and build'

parallel(

	'unit test' : {
		node('test_slave') {sh 'echo unit tests'}
	},
	'pact test' : {
		node('test_slave') {sh 'echo pact tests'}
	},
	'build image' : {
		node('test_slave') {sh 'echo build docker image'}
	}
)

stage 'State 3. development') 
	node('test_slave') {sh 'echo development'}
