stage 'Stage 1. Checkout repo'

node('test-slave') {
	//git 'https://github.com/yufanwan/microservice.git'
	sh 'svn checkout  https://github.com/yufanwan/microservice/trunk/event-composite-service/.'
}

stage 'State 2. test and build'

parallel(

	'unit test' : {
		node('test-slave') {sh 'echo unit tests'}
	},
	'pact test' : {
		node('test-slave') {sh 'echo pact tests'}
	},
	'build image' : {
		node('test-slave') {sh 'echo build docker image'}
	}
)

stage 'State 3. development'
	node('test-slave') {sh 'echo development'}
