FROM centos/java:8

WORKDIR /app

ADD ./build/libs/review-service-0.0.1.jar /app
RUN ln -s review-service-0.0.1.jar review-service-latest.jar

ADD ./wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it


CMD java -jar /app/review-service-latest.jar
